Broker="amqp://gw:gao123456@localhost:5672/"
ResultBackend="redis://gao123456xyt!@127.0.0.1:6379"
phone=18618184632
code=1234

sendJob:
	go run demo/taskManager/productor.go -broker=${Broker} -result=${ResultBackend} -phone=${phone} -code=${code}

sendJobs:
	go run demo/taskManager/productor.go -total=10000 -broker=${Broker} -result=${ResultBackend} -phone=${phone} -code=${code}

consumer:
	go run demo/taskManager/consumer.go -broker=${Broker} -result=${ResultBackend}

consumers:
	go run demo/taskManager/consumer.go -broker=${Broker} -result=${ResultBackend} -worker=10
